### ISSUE TITLE
准备转到组织了

### ISSUE THREAD

**Issue by ivaquero** [ivaquero/homebrew-chinese-prior#101]
创建了一个组织，打算转到组织里，我把两位都设为管理员，可以自行读写、加人等等 @Oscaner @Mrered 

https://github.com/Brewforge

有什么需要注意的么？我先在 README 里面说一下。

**Comment by Mrered** [comment]
1. 为了之后的发展，咱们应该写点模板，用于 Issues Discussions
2. 如果可以的话，咱们可以弄一个介绍网站，用于自我介绍和提供应用列表
